language: node_js
node_js:
  - "stable"
addons:
  chrome: stable
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
cache:
  directories:
  - node_modules
script:
  - ./node_modules/.bin/wdio wdio.conf.js
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 57157e5760b7835c020a133df94da9d19ee65539
  local_dir: build
  on:
    branch: master
