language: node_js
node_js:
  - "stable"
addons:
  chrome: beta
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-beta --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost:80
cache:
  directories:
  - node_modules
script:
  - ./node_modules/.bin/wdio wdio.conf.js
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 68da8fed70cf6e033ef27d9370119f6fd483e890
  local_dir: build
  on:
    branch: master